### ISSUE TITLE
convert png to jpg do not get the right picture

### ISSUE THREAD

**Issue by ChitaGideon** [devongovett/png-stream#2]
the png is this:

![test image](http://ac-7kfrdWcO.qiniudn.com/76e61af6-fa6a-9cf6-fa98-687e9f1535c5.png)

code:
```
  fs.createReadStream(file)
  .pipe(new PNGDecoder)
  //.pipe(new neuquant.Stream)
  .pipe(new JPEGEncoder)
  .pipe(fs.createWriteStream('indexed.jpg'));
```
and the convert result :
![result image](http://ac-7kfrdwco.qiniudn.com/2dda6db7-3b3f-cd41-083a-9d64fb3b40a6.jpg)

**Comment by devongovett** [comment]
If the png has an alpha channel, that could happen. You should try putting a [color transform](https://github.com/devongovett/color-transform) to rgb in the middle.

**Comment by ChitaGideon** [comment]
you are right
change my code to
```
  fs.createReadStream(file)
  .pipe(new PNGDecoder)
  .pipe(new ColorTransform('rgb'))
  .pipe(new JPEGEncoder)
  .pipe(fs.createWriteStream('indexed.jpg'));
```
anything make sence
